# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='asset_id',
            field=models.CharField(max_length=164, primary_key=True, serialize=False, verbose_name='资产编号'),
        ),
    ]
