# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180108_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='last_check_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.CheckInfo', verbose_name='上一次盘点时间'),
        ),
    ]
