# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180108_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconf',
            name='product_conf',
            field=models.CharField(default=' N/A ', max_length=64, verbose_name='配置信息'),
        ),
    ]
