# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180108_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinfo',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='盘点时间'),
        ),
    ]
