# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180108_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinfo',
            name='title',
            field=models.CharField(default='2017盘点', max_length=32, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
