# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_checkinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='last_check_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.CheckInfo', verbose_name='上一次盘点时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='title',
            field=models.CharField(default='N/A', max_length=32, verbose_name='Title'),
        ),
    ]
